tunnel: ad360029-e242-4123-888d-f156fc0bc701
credentials-file: /etc/cloudflared/credentials.json

ingress:
  - hostname: api.finpipe.app
    service: http://ws-relay:8080
  - service: http_status:404
