#!/usr/bin/env bash
# Pulls secrets from GCP Secret Manager and writes deploy/host/.env for compose.
#
# Auth: relies on whatever gcloud is currently authenticated as. On the homelab,
# activate the SA key first:
#   gcloud auth activate-service-account --key-file=$HOME/.config/finpipe/sa-key.json
# On the GCP VM, the attached SA is used automatically.
#
# Usage:
#   ./deploy/host/load_secrets.sh                # writes deploy/host/.env
#   ./deploy/host/load_secrets.sh /custom/.env   # writes to a custom path
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUT_FILE="${1:-$REPO_ROOT/deploy/host/.env}"
PROJECT_ID="${GCP_PROJECT_ID:?set GCP_PROJECT_ID (e.g. export GCP_PROJECT_ID=finpipe-prod)}"

# Map of compose env var -> Secret Manager secret name. Add rows as needed.
declare -A SECRETS=(
  [POSTGRES_PASSWORD]=finpipe-postgres-password
  [DAGSTER_PG_PASSWORD]=finpipe-dagster-postgres-password
  [JWT_SECRET]=finpipe-jwt-secret
  [MASSIVE_API_KEY]=massive-api-key
  [CLOUDFLARED_TOKEN]=finpipe-cloudflared-token
)

# Non-secret config that ships in plaintext alongside the secret env file.
declare -A PLAIN=(
  [POSTGRES_USER]=finpipe
  [POSTGRES_DB]=finpipe
  [GCP_PROJECT_ID]="$PROJECT_ID"
  [GCS_LAKEHOUSE_BUCKET]="${GCS_LAKEHOUSE_BUCKET:-}"
  [GCS_DATA_BUCKET]="${GCS_DATA_BUCKET:-}"
  [DATAPROC_REGION]="${DATAPROC_REGION:-us-central1}"
  [DATAPROC_SERVICE_ACCOUNT]="${DATAPROC_SERVICE_ACCOUNT:-}"
  [SA_KEY_PATH]="${SA_KEY_PATH:-}"
  [GOOGLE_APPLICATION_CREDENTIALS]="${GOOGLE_APPLICATION_CREDENTIALS:-}"
)

mkdir -p "$(dirname "$OUT_FILE")"
umask 077
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

{
  echo "# Generated by load_secrets.sh on $(date -u +%FT%TZ) — do not commit"
  for k in "${!PLAIN[@]}"; do
    printf '%s=%s\n' "$k" "${PLAIN[$k]}"
  done
  for k in "${!SECRETS[@]}"; do
    name="${SECRETS[$k]}"
    val="$(gcloud secrets versions access latest \
      --secret="$name" --project="$PROJECT_ID" 2>/dev/null)" \
      || { echo "missing secret: $name" >&2; exit 1; }
    printf '%s=%s\n' "$k" "$val"
  done
} > "$TMP"

mv "$TMP" "$OUT_FILE"
chmod 600 "$OUT_FILE"
echo "wrote $OUT_FILE"
